### ISSUE TITLE
Retrieve mediastatus

### ISSUE THREAD

**Issue by lsiepel** [DigitalMediaServer/Cast-API#1]
For a project i'm experimenting with a replacement to  and this fork seems to solve most issues we have. Most of the handling is similar, but the session MediaStatus is pretty different. I have this requirement to show the title in the media player (appId: CC1AD845).

Previously we called:
`chromeCast.load(title, null, url, mimeType);
`
This has changed to
```
MediaBuilder builder = new MediaBuilder(url, mimeType, StreamType.NONE);
session.load(builder, true, 0.0, false);
```

But i don't see an obvious place/call to add this title so it get shown. Can someone help me out here?

**Comment by Nadahar** [comment]
I'm not sure I understand what you're asking.

`MediaStatus` is returned as the result of several "commands" like `load`, `pause`, `play`, `seek`, `stopMedia` and `setMediaVolume`, so that you can see the result of the command sent. But, if you just want to read the `MediaStatus`, not send a command, you can simply use `Channel.getMediaStatus()`:

https://github.com/DigitalMediaServer/Cast-API/blob/3030d561d8445b2c6c244174c282ce699d08d2a5/src/main/java/org/digitalmediaserver/cast/Channel.java#L861-L901

Does that answer your question?

**Comment by lsiepel** [comment]
Sorry I wasn’t clear. The MediaState issue was fixed I should not have mentioned it. . Only the title requirement related to the the load call is left. 
Before this was part of the method signature, but I guess now it is hidden behind one of the builder options?

**Comment by Nadahar** [comment]
I assume that you mean the title that is shown on the Chromecast then? The data structures mirrors those documented by Google's API as much as possible, and I don't remember all the details now, but I think you need to use [Metadata](https://github.com/DigitalMediaServer/Cast-API/blob/master/src/main/java/org/digitalmediaserver/cast/Metadata.java) to add things like a title to a [Media](https://github.com/DigitalMediaServer/Cast-API/blob/master/src/main/java/org/digitalmediaserver/cast/Media.java).

I've added some "standard" metadata keys that I've found as constants that can be utilized easily, but the key is just a string so it could be anything. I think the standard "player" use this key though: https://github.com/DigitalMediaServer/Cast-API/blob/3030d561d8445b2c6c244174c282ce699d08d2a5/src/main/java/org/digitalmediaserver/cast/Metadata.java#L184-L189

**Comment by lsiepel** [comment]
re-opened, because i have a related question. I cannot find it on the Google APi docs. would it in some way be possible to retrieve a list of installed/available applications? One can test if the app is available according `chromeCast.isApplicationAvailable(appId)` , but to build a preselectable list of apps, i would like to retrieve it from the device.

**Comment by Nadahar** [comment]
I don't think the list is available. Google's idea, as far as I understand, is that developers develop their own "cast applications", which are registered and assigned unique IDs by Google. Only the developers of the given "app" will know the ID of "their app".

If you pay for a Google developer ID and have a place to host the "app", anybody can register and make their own as far as I understand it.

Everybody else will have to make do with the "default media player" whose ID is public knowledge.

**Comment by lsiepel** [comment]
Allready thought so :-( i just like to start  and do basic control on other apps. Thanks for you quick support!
